import { useState } from 'react';
import { Action, Choices, Copy, Page, useCopy } from '@/components/onboarding/DemoUI';
import { useExperience } from '@/context/ExperienceContext';
import { useLocale } from '@/context/LocaleContext';
export default function Installation() {
    const e = useExperience();
    const t = useCopy();
    const { region } = useLocale();
    const [channel, setChannel] = useState('store');
    const [step, setStep] = useState(0);
    const [stopped, setStopped] = useState(false);
    const steps = e.platform === 'ios' ? [t('在 App Store 找到 MotionStation', 'Find MotionStation in the App Store'), t('点击获取，按系统提示验证 Apple 账户', 'Tap Get and authenticate your Apple Account as prompted'), t('安装完成，点击打开', 'Installation complete. Tap Open'), t('进入欢迎页，阅读用户协议与隐私政策', 'Open Welcome and review the terms and privacy policy')] : channel === 'apk' ? [t('从可信发行渠道下载安装包', 'Download the APK from a trusted distribution channel'), t('若系统要求，为下载来源应用（如浏览器）允许安装；也可取消', 'If prompted, allow installation for the source app, such as your browser, or cancel'), t('由系统安装器显示确认，审核后选择安装', 'Review the system installer confirmation and choose Install'), t('安装完成，首次打开后进入欢迎页', 'After installation, the first launch opens Welcome')] : [region === 'CN' ? t('在发行的安卓应用商店找到 MotionStation', 'Find MotionStation in the distribution app store') : t('在 Google Play 找到 MotionStation', 'Find MotionStation on Google Play'), t('点击安装，由商店完成安装', 'Tap Install; the store handles installation'), t('安装完成，点击打开', 'Installation complete. Tap Open'), t('进入欢迎页，阅读用户协议与隐私政策', 'Open Welcome and review the terms and privacy policy')];
    return <Page title={t('安装流程演示', 'Installation walkthrough')}><Copy>{t('此处是独立流程说明，不会安装应用或修改系统设置。实际提示由系统版本与发行渠道决定。', 'This walkthrough does not install apps or change settings. Actual prompts depend on the OS and distribution channel.')}</Copy><Choices values={[['android', 'Android'], ['ios', 'iOS']]} selected={e.platform} onSelect={p => { e.setPlatform(p); setStep(0); setStopped(false); }}/>{e.platform === 'android' && <Choices values={[['store', t('应用商店', 'App store')], ['apk', 'APK']]} selected={channel} onSelect={c => { setChannel(c); setStep(0); setStopped(false); }}/>}<Copy>{t('系统流程示意', 'System flow illustration')} · {step + 1} / {steps.length}</Copy><Copy title>{stopped ? t('安装已取消', 'Installation cancelled') : steps[step]}</Copy><Copy>{e.platform === 'ios' ? t('普通 App Store 安装不需要企业开发者信任。安装与相机、蓝牙、本地网络授权是独立流程。', 'Regular App Store installs do not require enterprise developer trust. Installation is separate from camera, Bluetooth and local network access.') : t('“允许此来源安装”属于来源应用的系统设置，不是 MotionStation 申请的业务权限。无需关闭系统安全保护。', 'Allowing installation from a source is a system setting for that source app, not a MotionStation runtime permission. Do not disable system security protection.')}</Copy><Action label={stopped || step === steps.length - 1 ? t('重新演示', 'Restart') : t('下一步', 'Next')} onPress={() => { setStopped(false); setStep(stopped || step === steps.length - 1 ? 0 : step + 1); }}/>{!stopped && step < steps.length - 1 && <Action secondary label={t('取消安装（演示）', 'Cancel installation (demo)')} onPress={() => setStopped(true)}/>}</Page>;
}
