import { useMemo } from "react";
import { Platform, StyleSheet } from "react-native";
import { useTheme } from "@/context/ThemeContext";
import { ColorPalette, radius, spacing, typography } from "@/theme";

export function createAuthStyles(colors: ColorPalette) {
  return StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxxl,
  },
  headerBar: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
  },
  headerBarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 44,
  },
  localeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.surfaceElevated,
  },
  localeButtonGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  localeButtonText: {
    ...typography.caption,
    color: colors.textPrimary,
    fontWeight: "600",
  },
  card: {
    padding: spacing.xl,
    gap: spacing.lg,
  },
  title: {
    ...typography.title,
    color: colors.textPrimary,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  titleFlex: {
    flex: 1,
  },
  titleAction: {
    flexShrink: 0,
    paddingVertical: spacing.xs,
  },
  titleActionText: {
    ...typography.caption,
    color: colors.accent,
    fontWeight: "600",
  },
  subtitle: {
    ...typography.caption,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  separator: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: "center",
  },
  field: {
    gap: spacing.sm,
  },
  label: {
    ...typography.label,
    color: colors.textSecondary,
  },
  sublabel: {
    ...typography.caption,
    color: colors.textMuted,
  },
  input: {
    ...typography.body,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minHeight: 52,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  inputFlex: {
    flex: 1,
  },
  primaryButton: {
    marginTop: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    paddingVertical: spacing.lg,
    minHeight: 52,
  },
  primaryButtonText: {
    ...typography.subtitle,
    color: colors.accentText,
  },
  secondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    minHeight: 52,
    minWidth: 108,
  },
  secondaryButtonDisabled: {
    opacity: 0.55,
  },
  secondaryButtonText: {
    ...typography.label,
    color: colors.textPrimary,
  },
  linkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: spacing.sm,
  },
  linkButton: {
    paddingVertical: spacing.sm,
  },
  linkText: {
    ...typography.caption,
    color: colors.accent,
  },
  footLinksWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  switchLinkRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginTop: spacing.md,
    paddingVertical: spacing.sm,
  },
  switchLinkPrefix: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  switchLinkAction: {
    ...typography.caption,
    color: colors.accent,
    fontWeight: "600",
  },
  socialSection: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  socialSeparator: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: "center",
  },
  socialRow: {
    flexDirection: "row",
    gap: spacing.md,
  },
  socialButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    minHeight: 48,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.surfaceElevated,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
  },
  socialButtonText: {
    ...typography.caption,
    color: colors.textPrimary,
    fontWeight: "600",
  },
  quickLoginCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.lg,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.surfaceElevated,
  },
  quickLoginAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  quickLoginAvatarText: {
    ...typography.subtitle,
    color: colors.textPrimary,
  },
  quickLoginMeta: {
    flex: 1,
    gap: spacing.xs,
  },
  quickLoginName: {
    ...typography.subtitle,
    color: colors.textPrimary,
  },
  quickLoginHint: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  methodTabs: {
    flexDirection: "row",
    gap: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.pill,
    padding: spacing.xs,
  },
  methodTab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.md,
    borderRadius: radius.pill,
  },
  methodTabActive: {
    backgroundColor: colors.surfaceElevated,
  },
  methodTabText: {
    ...typography.caption,
    color: colors.textMuted,
  },
  methodTabTextActive: {
    color: colors.textPrimary,
    fontWeight: "600",
  },
  policyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  policyText: {
    flex: 1,
    ...typography.caption,
    color: colors.textSecondary,
    lineHeight: 22,
  },
  policyLink: {
    color: colors.accent,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  dateRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  datePart: {
    flex: 1,
    gap: spacing.xs,
  },
  selectButton: {
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    minHeight: 52,
    justifyContent: "center",
  },
  selectButtonText: {
    ...typography.body,
    color: colors.textPrimary,
  },
  unitToggle: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  unitButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  unitButtonActive: {
    backgroundColor: colors.accentGlass,
    borderColor: colors.accent,
  },
  unitButtonText: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  unitButtonTextActive: {
    color: colors.accent,
    fontWeight: "600",
  },
  genderRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  genderOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceElevated,
  },
  genderOptionActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentGlass,
  },
  genderOptionText: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  genderOptionTextActive: {
    color: colors.accent,
    fontWeight: "600",
  },
  scanEntryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.glassBorder,
    backgroundColor: colors.surfaceElevated,
  },
  scanEntryIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentGlass,
  },
  scanEntryMeta: {
    flex: 1,
    gap: spacing.xs,
  },
  scanEntryTitle: {
    ...typography.subtitle,
    color: colors.textPrimary,
  },
  scanEntryHint: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  scanBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
    gap: spacing.xxl,
  },
  scanHint: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: "center",
  },
  scanFrame: {
    width: 260,
    height: 260,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  scanFrameCorner: {
    position: "absolute",
    width: 28,
    height: 28,
    borderColor: colors.accent,
  },
  scanFrameCornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
  },
  scanFrameCornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
  },
  scanFrameCornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
  },
  scanFrameCornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
  },
  scanQrPlaceholder: {
    width: 180,
    height: 180,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  scanLine: {
    position: "absolute",
    left: 12,
    right: 12,
    height: 2,
    backgroundColor: colors.accent,
    opacity: 0.9,
  },
  cinematicScroll: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  cinematicFlex: {
    flex: 1,
    backgroundColor: "transparent",
  },
  cinematicLogoWrap: {
    alignItems: "center",
    marginBottom: spacing.xl,
  },
  cinematicGreeting: {
    ...typography.hero,
    color: "#FFFFFF",
    textAlign: "center",
  },
  cinematicCard: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
    ...Platform.select({
      web: {
        backdropFilter: "blur(22px)",
        boxShadow: "0 18px 40px rgba(0,0,0,0.28)",
      },
      default: {
        shadowColor: "#000000",
        shadowOpacity: 0.22,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 10 },
        elevation: 10,
      },
    }),
  },
  cinematicTitle: {
    ...typography.title,
    color: "#FFFFFF",
  },
  cinematicSubtitle: {
    ...typography.caption,
    color: "rgba(255,255,255,0.65)",
    marginTop: spacing.xs,
  },
  cinematicTitleActionText: {
    ...typography.caption,
    color: colors.accentBright,
    fontWeight: "600",
  },
  cinematicLabel: {
    ...typography.label,
    color: "rgba(255,255,255,0.72)",
  },
  cinematicInputShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    minHeight: 52,
    borderRadius: radius.lg,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: spacing.md,
  },
  cinematicInput: {
    ...typography.body,
    color: "#FFFFFF",
    flex: 1,
    paddingVertical: spacing.md,
    minHeight: 52,
  },
  cinematicPrimaryButton: {
    marginTop: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
    borderRadius: radius.pill,
    paddingVertical: spacing.lg,
    minHeight: 54,
  },
  cinematicPrimaryButtonText: {
    ...typography.subtitle,
    color: colors.accentText,
  },
  cinematicSecondaryButton: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    minHeight: 40,
    minWidth: 96,
  },
  cinematicSecondaryButtonText: {
    ...typography.label,
    color: "#FFFFFF",
    fontSize: 13,
  },
  cinematicPolicyText: {
    flex: 1,
    ...typography.caption,
    color: "rgba(255,255,255,0.68)",
    lineHeight: 22,
  },
  cinematicPolicyLink: {
    color: colors.accentBright,
    fontWeight: "600",
  },
  cinematicCheckbox: {
    width: 22,
    height: 22,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    backgroundColor: "transparent",
  },
  cinematicSwitchPrefix: {
    ...typography.caption,
    color: "rgba(255,255,255,0.62)",
  },
  cinematicSwitchAction: {
    ...typography.caption,
    color: colors.accentBright,
    fontWeight: "700",
  },
  cinematicSocialSection: {
    gap: spacing.md,
    marginTop: spacing.xs,
  },
  cinematicDividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  cinematicDividerLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  cinematicSocialSeparator: {
    ...typography.caption,
    color: "rgba(255,255,255,0.45)",
    fontSize: 13,
  },
  cinematicSocialRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: spacing.lg,
  },
  cinematicSocialCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  cinematicLinkText: {
    ...typography.caption,
    color: colors.accentBright,
    fontWeight: "600",
  },
});
}

export function useAuthStyles() {
  const { colors } = useTheme();
  return useMemo(() => createAuthStyles(colors), [colors]);
}
